name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Nodes
        uses: actions/setup-node@v3
      - run: npm ci
      - run: cd src/examples
      - run: npm test
